language: c

os:
- linux
- osx
- freebsd

dist: focal

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - cmake

compiler:
- gcc
- clang

before_script:
- mkdir build
- cd build
- cmake -DENABLE_TESTS=1 -DENABLE_COVERAGE=1 ..

script:
 - make
 - make test

after_success:
- bash <(curl -s https://codecov.io/bash)
